name: Build

on: [push, pull_request]

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Test apache2
      run: |
        sudo apt-get update -y
        sudo apt-get install apache2 -y
        sudo mv etc /etc
        sudo service apache2 restart
        sudo service apache2 status
