name: Build

on: [push, pull_request]

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Test apache2
      run: |
        sudo apt-get update -y
        sudo apt-get install apache2 -y
        sudo rm /etc/apache2/sites-enabled/*
        sudo rm /etc/apache2/sites-available/*
        sudo cp etc/apache2/sites-available/* /etc/apache2/sites-enabled/
        sudo cp etc/apache2/sites-available/* /etc/apache2/sites-available/
        sudo service apache2 restart || true
        sudo service apache2 status || true
        sudo a2enmod proxy
        sudo service apache2 restart || true
        sudo journalctl -e --no-pager || true
